import localFont from 'next/font/local';
import './globals.css';
import Link from 'next/link';
import { auth } from '@/auth';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const session = await auth();
  const userImage = session?.user?.image;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased px-4 flex flex-col min-h-screen`}
      >
        <nav className="flex gap-4 items-center justify-center mx-auto bg-gray-100 p-4 mb-10 w-full">
          <Link href="/" className="flex-1">
            Home
          </Link>
          <Link href="/about">About</Link>
          <Link href="/articles">Articles</Link>
          <Link className="flex items-center gap-1" href="/panel">
            {userImage && <img src={userImage} className="w-8 rounded-full" />}
            Admin Panel
          </Link>
        </nav>
        <main className="flex-grow">{children}</main>

        <footer className="text-center p-4 mt-20 border-t">
          <p className="text-sm text-gray-500">
            &copy; {new Date().getFullYear()} My Blog. All rights reserved.
          </p>
        </footer>
      </body>
    </html>
  );
}
